"""add raw_logs and processed_logs tables

Revision ID: e75853ce4586
Revises: f4962bf73ef7
Create Date: 2026-01-25 15:42:35.442944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75853ce4586'
down_revision = 'f4962bf73ef7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processed_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_log_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('destination_ip', sa.String(length=45), nullable=True),
    sa.Column('destination_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('attack_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['raw_log_id'], ['raw_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_logs')
    op.drop_table('raw_logs')
    # ### end Alembic commands ###
